# Generated by Django 4.2.3 on 2023-07-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('dep', models.CharField(max_length=70)),
            ],
        ),
    ]
