# Generated by Django 4.2.3 on 2023-07-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0003_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
