# Generated by Django 4.2.3 on 2023-08-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0006_complaindetails_complaintable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('npwp', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=100)),
                ('top_id', models.PositiveSmallIntegerField()),
                ('type', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(db_comment='9-> di hold pengiriman')),
                ('efakturaddress_type', models.PositiveIntegerField(db_comment='1-> Alamat mengacu ke NPWP pusat, 2->Alamat mengacu ke alamat kirim')),
                ('rating', models.PositiveIntegerField()),
                ('keterangan', models.CharField(blank=True, max_length=250, null=True)),
                ('balance_ar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_ap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_by', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name2', models.CharField(blank=True, db_comment='Untuk Item Code', max_length=250, null=True)),
                ('category_id', models.PositiveIntegerField()),
                ('type_id', models.PositiveIntegerField()),
                ('unit_fg', models.CharField(db_comment='PCS, ROLL, KG', max_length=5)),
                ('unit_po', models.CharField(db_comment='PCS, ROLL, KG', max_length=5)),
                ('quantity_per_ufg', models.DecimalField(db_comment='How many Unit_PO in one unit of FG. Example: 12500 PCS PER ROLL', decimal_places=2, max_digits=10)),
                ('buffered_quantity', models.DecimalField(blank=True, db_comment='How many we already have buffer stock (in unit_fg)', decimal_places=2, max_digits=10, null=True)),
                ('number_color', models.PositiveIntegerField(db_comment='Berapa warna')),
                ('number_material', models.PositiveIntegerField(db_comment='Berapa material')),
                ('width_fg', models.DecimalField(db_comment='Lebar Produk Jadi', decimal_places=2, max_digits=10)),
                ('width_design', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_fg', models.DecimalField(db_comment='TInggi Produk jadi', decimal_places=2, max_digits=10)),
                ('height_design', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_fg', models.PositiveSmallIntegerField(db_comment='Bila unit_fg dalam bentuk Roll, 1 roll ada berapa meter')),
                ('bagmaking_up', models.PositiveIntegerField()),
                ('sideseal_width', models.DecimalField(db_comment='For 3-side seal, std pouch, diapers', decimal_places=2, max_digits=10)),
                ('bottomseal_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sidegusset_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottomgusset_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revisi', models.PositiveIntegerField(db_comment='Revisi keberapa. Contoh: revisi Nomor MD')),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('revisi_notes', models.TextField(blank=True, db_comment='Keterangan Revisi', null=True)),
                ('status', models.PositiveIntegerField(db_comment='0-> obsolete, 1->active, 2->inactive')),
                ('created_by', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qc.companies')),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qc.employees')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
