# Generated by Django 4.2.3 on 2023-08-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0007_companies_employees_products_delete_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
    ]
