# Generated by Django 4.2.3 on 2023-08-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0008_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
