# Generated by Django 4.2.3 on 2023-08-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0009_alter_products_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcCapa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complain_id', models.PositiveIntegerField()),
                ('complaindetail_id', models.PositiveBigIntegerField()),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('perventive_action', models.TextField(blank=True, null=True)),
                ('pic', models.CharField(blank=True, db_column='PIC', max_length=30, null=True)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('verifikasi', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ic_capa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcProblemanalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complain_id', models.PositiveIntegerField()),
                ('complaindetail_id', models.PositiveBigIntegerField()),
                ('analysis_category', models.CharField(db_comment='MAN, MACHINE, METHOD, MATERIAL, ENVIRONMENT', max_length=25)),
                ('analysis_description', models.TextField()),
            ],
            options={
                'db_table': 'ic_problemanalysis',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
