# Generated by Django 4.2.3 on 2023-09-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0010_iccapa_icproblemanalysis_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.SmallIntegerField()),
                ('customer_id', models.IntegerField(db_comment='customer who complains')),
                ('nomor_document', models.CharField(db_comment='nomor IC', max_length=200)),
                ('document_date', models.DateField(db_comment='tanggal IC')),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complain_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ComplainTable',
        ),
    ]
